title: MARS JUSTICE
description: FOR THE FUTURE. FOR CHILDREN âœŠğŸ»â¤ï¸ğŸ‡ºğŸ‡¸

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

repository: MarsJustice/MarsJustice.github.io

url: "https://MarsJustice.co"
baseurl: ""