title: MARS JUSTICE
description: ğŸ”´ MAKE AMERICA FREE AGAIN âš”ï¸â¤ï¸ğŸ‡ºğŸ‡¸ 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

repository: MarsJustice/MarsJustice.github.io

url: "https://MarsJustice.co"
baseurl: ""